export const products = [
    {
        id: 1,
        title: "Bridge Jacket",
        image: "../images/jacket.png",
        price: "199",
        isFavorite: false,
    },
    {
        id: 2,
        title: "Jeep 4wd",
        image: "../images/jeep.png",
        price: "128,000",
        isFavorite: true,
    },
    {
        id: 3,
        title: "Bond Lighter",
        image: "../images/lighter.png",
        price: "27",
        isFavorite: false,
    },
    {
        id: 4,
        title: "J-lo Perfume",
        image: "../images/perfume.png",
        price: "99",
        isFavorite: false,
    },
    {
        id: 5,
        title: "Suzuki B-max",
        image: "../images/scooter.png",
        price: "1,400",
        isFavorite: false,
    },
    {
        id: 6,
        title: "Joneses Sofa",
        image: "../images/sofa.png",
        price: "1,700",
        isFavorite: false,
    },
    {
        id: 7,
        title: "Iron Wallet",
        image: "../images/wallet.png",
        price: "213",
        isFavorite: false,
    },
];
